[tools]
dart = "3.9.4"

[env]
API_KEY_GEMINI=""
API_KEY_CHATGPT=""
OLLAMA_MODEL="phi4-mini:3.8b"

[tasks]
run = "dart run bin/dnose.dart"
test = "dart test"
build = "dart run build_runner clean && dart run build_runner build --delete-conflicting-outputs"
format = "dart format ."
analyze = "dart analyze"    
compile = "dart compile exe bin/dnose.dart -o dnose.run"
run_compiled = "./dnose.run"
