name: dnose
description: Dart Test Smell Detector
version: 1.0.0
repository: https://github.com/tassiovirginio/dnose

environment:
  sdk: ^3.3.4

dependencies:
  logging: ^1.2.0
  shelf_plus: ^1.9.2
  yaml: 3.1.2
  crypto: 3.0.3
  analyzer: ^6.4.1
  shelf_cors_headers: ^0.1.5
  git_clone: ^1.2.0
  google_generative_ai: ^0.4.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
