name: dnose
description: Dart Test Smell Detector
version: 1.0.0
repository: https://github.com/tassiovirginio/dnose

environment:
  sdk: ^3.3.3

dependencies:
  logging: ^1.2.0
  shelf_plus: ^1.9.2
  yaml: 3.1.2
  crypto: 3.0.3
  analyzer: ^6.4.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  analyzer: ^6.4.1
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
