name: dnose
description: Dart Test Smell Detector
version: 1.0.0
repository: https://github.com/tassiovirginio/dnose

environment:
  sdk: ^3.4.0

dependencies:
  logging: ^1.2.0
  shelf_plus: ^1.9.2
  yaml: ^3.1.2
  crypto: ^3.0.3
  analyzer: ^6.5.0
  shelf_cors_headers: ^0.1.5
  git_clone: ^1.2.0
  google_generative_ai: ^0.4.1
  langchain: ^0.7.1
  langchain_openai: ^0.6.1+1
  statistics: ^1.1.0
  sqlite3: ^2.4.3
  process_run: ^0.14.2
  scidart: ^0.0.2-dev.12
  properties: ^2.1.0
  langchain_ollama: ^0.2.2
  git: ^2.3.0
  basics: ^0.10.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
  build_runner: ^2.4.10
  build_web_compilers: ^4.0.10


linter:
  rules:
    - camel_case_types
    - empty_constructor_bodies
    - always_use_package_imports