name: dnose
description: Dart Test Smell Detector
version: 1.0.0
repository: https://github.com/tassiovirginio/dnose

environment:
  sdk: '>=3.7.0-0 <4.0.0'

dependencies:
  sentiment_dart: ^0.0.5
  analyzer: ^7.3.0
  basics: ^0.10.0
  crypto: ^3.0.5
  csv: ^6.0.0
  git: ^2.3.1
  git_clone: ^1.2.0
  google_generative_ai: ^0.4.5
  langchain: ^0.7.4
  langchain_ollama: ^0.3.0
  langchain_openai: ^0.7.0
  logging: ^1.2.0
  process_run: ^1.1.0
  properties: ^2.1.0
  scidart: ^0.0.2-dev.12
  shelf_cors_headers: ^0.1.5
  shelf_plus: ^1.9.2
#  shelf_web_socket: ^1.0.4
  sqlite3: ^2.4.5
  statistics: ^1.2.0
  yaml: ^3.1.2
  custom_lint: ^0.7.3
  analyzer_plugin: ^0.12.0
  custom_lint_builder: ^0.7.3
  path: ^1.9.1
  intl: ^0.20.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
  build_runner: ^2.4.11
  build_web_compilers: ^4.0.11


linter:
  rules:
    - camel_case_types
    - empty_constructor_bodies
    - always_use_package_imports