void main() {
  var lista =
      "adaptive_dialog,Animated-Text-Kit,audioplayers,audio_service,auto_size_text,awesome_notifications,backdrop,beamer,betterplayer,bitsdojo_window,bloc,build,charts,chewie,collection,convex_bottom_bar,CountryCodePicker,crypto,curved_navigation_bar,dart_pdf,dart-uuid,dartz,dio,easy_localization,encrypt,equatable,excel,extended_image,firebase-android-sdk,flame,fl_chart,flex_color_scheme,fluent_ui,Flutter-AssetsAudioPlayer,flutter_background_fetch,flutter_badges,flutter_blue,flutter_blurhash,flutter_cached_network_image,flutter_cache_manager,flutter_carousel_slider,flutter_device_preview,flutter_downloader,flutter_easyloading,flutter-examples,flutter-facebook-auth,flutter_file_picker,flutterfire,flutter_form_builder,flutter-geocoding,flutter-geolocator,flutter_google_places,flutter_hooks,flutter_html,flutter_image_compress,flutter_image_cropper,flutter_inappwebview,flutter-intro-slider,flutter_keyboard_actions,flutter_keyboard_visibility,flutter_launcher_icons,flutter_local_notifications,flutterlocation,flutter_login,flutter_map,flutter_native_splash,Flutter-Neumorphic,flutter_percent_indicator,flutter-permission-handler,flutter_platform_widgets,flutter_pulltorefresh,flutter-quill,flutter_rating_bar,flutter_screenutil,flutter_secure_storage,flutter-settings-ui,flutter_shimmer,flutter_showcaseview,flutter_slidable,flutter_sound,flutter_speed_dial,flutter_spinkit,flutter_staggered_grid_view,flutter_stripe,flutter_svg,flutter_swiper,flutter_tags,FlutterToast,flutter_tts,flutter_typeahead,flutter-webrtc,flutter-widgets,flutter_workmanager,flutter_zoom_drawer,font_awesome_flutter,freezed,get,get_it,get_storage,getwidget,googleads-mobile-flutter,googleapis,google-fonts-flutter,google_nav_bar,grouped_list,hive,http,image,image_downloader,in_app_review,injectable,intl,isar,json_serializable.dart,just_audio,logger,mobx.dart,mockito,mocktail,modal_bottom_sheet,moor,open_file,packages,path,PersistentBottomNavBar,photo_view,pin_code_fields,plugins,plus_plugins,pluto_grid,provider,qr_code_scanner,qr.flutter,responsive_builder,ResponsiveFramework,retrofit.dart,rflutter_alert,rive-flutter,riverpod,rxdart,salomon_bottom_bar,simple_animations,sizer,sliding_up_panel,socket.io-client-dart,sqflite,stacked,supercharged,table_calendar,timelines,timeline_tile,tutorial_coach_mark,upgrader,VelocityX,wolt_modal_sheet,youtube_player_flutter".split(",");

  var lista2 =
      "get,provider,flutter_native_splash,http,dio,bloc,flutter_launcher_icons,flutter_local_notifications,flutter_cached_network_image,fl_chart,hive,google-fonts-flutter,flutter-geolocator,flutter_slidable,flutter_carousel_slider,intl,flutter-permission-handler,flutter_svg,Animated-Text-Kit,sqflite,flutter_shimmer,auto_size_text,font_awesome_flutter,flutter_screenutil,flutter_file_picker,flutter_staggered_grid_view,flutter_spinkit,get_it,freezed,flutter_device_preview,flutter_secure_storage,FlutterToast,just_audio,flutterfire,json_serializable.dart,flutter_badges,riverpod,modal_bottom_sheet,flutter-widgets,logger,easy_localization,equatable,awesome_notifications,audioplayers,ResponsiveFramework,flutterlocation,photo_view,table_calendar,sliding_up_panel,fluent_ui,flutter_pulltorefresh,convex_bottom_bar,dart_pdf,flex_color_scheme,rxdart,flutter_percent_indicator,flutter_form_builder,flutter_showcaseview,flutter_inappwebview,dart-uuid,flutter_rating_bar,getwidget,googleads-mobile-flutter,isar,pin_code_fields,flutter_image_cropper,flutter_hooks,PersistentBottomNavBar,flutter_easyloading,qr_code_scanner,qr.flutter,upgrader,flutter_workmanager,chewie,build,flame,flutter_html,simple_animations,flutter_typeahead,in_app_review,curved_navigation_bar,extended_image,flutter_map,flutter_swiper,timeline_tile,retrofit.dart,Flutter-Neumorphic,get_storage,rive-flutter,flutter-quill,moor,timelines,crypto,sizer,responsive_builder,flutter_cache_manager,flutter_blurhash,image,path,flutter_downloader,youtube_player_flutter,google_nav_bar,stacked,flutter_image_compress,grouped_list,VelocityX,flutter_sound,flutter_login,dartz,socket.io-client-dart,mockito,flutter-facebook-auth,beamer,flutter_tags,flutter_google_places,backdrop,charts,tutorial_coach_mark,mobx.dart,flutter_speed_dial,flutter_tts,flutter_stripe,injectable,collection,audio_service,betterplayer,flutter_platform_widgets,firebase-android-sdk,flutter-geocoding,flutter-intro-slider,Flutter-AssetsAudioPlayer,flutter_background_fetch,flutter-webrtc,flutter_keyboard_actions,rflutter_alert,mocktail,flutter_zoom_drawer,excel,googleapis,flutter_blue,adaptive_dialog,salomon_bottom_bar,encrypt,flutter_keyboard_visibility,bitsdojo_window,wolt_modal_sheet,pluto_grid,supercharged,flutter-settings-ui,open_file,CountryCodePicker,image_downloader,photo_view,packages,plugins,plus_plugins,flutter-examples".split(",");

  print(lista.length);
  print(lista2.length);

  for(var i in lista2){
    if(lista.contains(i) == false){
      print("==> ${i}");
    }
  }

  }