import 'package:analyzer/dart/ast/ast.dart';
import 'package:dnose/detectors/abstract_detector.dart';
import 'package:dnose/models/test_class.dart';
import 'package:dnose/models/test_smell.dart';

class DefaultTestDetector extends AbstractDetector {
  @override
  get testSmellName => "Default Test";

  @override
  List<TestSmell> detect(
    ExpressionStatement e,
    TestClass testClass,
    String testName,
  ) {
    this.testSmells = [];
    this.testClass = testClass;
    this.testName = testName;
    this.codeTest = e.toSource();
    this.startTest = testClass.lineNumber(e.offset);
    this.endTest = testClass.lineNumber(e.end);

    if (_isDefaultFlutterTest(e, testName)) {
      testSmells.add(createSmell(e));
    }

    return testSmells;
  }

  bool _isDefaultFlutterTest(ExpressionStatement e, String testName) {
    if (e.expression is! MethodInvocation) return false;
    var methodInvocation = e.expression as MethodInvocation;

    if (methodInvocation.methodName.name != 'testWidgets') return false;
    if (!testName.contains('Counter increments smoke test')) return false;

    if (methodInvocation.argumentList.arguments.length < 2) return false;
    var functionExpr = methodInvocation.argumentList.arguments[1];

    if (functionExpr is! FunctionExpression) return false;

    String bodyText = functionExpr.body.toSource().toLowerCase();

    bool hasPumpWidget = bodyText.contains('pumpwidget');
    bool hasFindText = bodyText.contains('find.text');
    bool hasFindsOneWidget = bodyText.contains('findsonewidget');
    bool hasFindsNothing = bodyText.contains('findsnothing');
    bool hasTap = bodyText.contains('tap');
    bool hasByIcon = bodyText.contains('byicon');
    bool hasIconsAdd = bodyText.contains('icons.add');

    return hasPumpWidget &&
        hasFindText &&
        hasFindsOneWidget &&
        hasFindsNothing &&
        hasTap &&
        hasByIcon &&
        hasIconsAdd;
  }

  @override
  String getDescription() {
    return '''
        Occurs when a test method contains the default Flutter counter test code that was
        auto-generated by Flutter. This indicates that the test has not been customized
        for the specific application and may not be testing meaningful functionality.
        Such tests should be modified or removed to ensure proper test coverage.
        ''';
  }

  @override
  String getExample() {
    return '''
        testWidgets('Counter increments smoke test', (WidgetTester tester) async {
          // Build our app and trigger a frame.
          await tester.pumpWidget(new MyApp());

          // Verify that our counter starts at 0.
          expect(find.text('0'), findsOneWidget);
          expect(find.text('1'), findsNothing);

          // Tap the '+' icon and trigger a frame.
          await tester.tap(find.byIcon(Icons.add));
          await tester.pump();

          // Verify that our counter has incremented.
          expect(find.text('0'), findsNothing);
          expect(find.text('1'), findsOneWidget);
        });
        ''';
  }
}
