name: Build and Release

on:
  release:
    types: [created, published, edited]

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Get dependencies
        run: dart pub get

      - name: Run build runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Compile Dart server
        run: dart compile exe bin/dnose.dart -o target/dnose_linux_amd64.exe

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/dnose_linux_amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

