name: Build and Release Multi-Platform

on:
  release:
    types: [created, published, edited]

jobs:
  build-release-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessário para o GITHUB_TOKEN fazer upload de assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Get dependencies
        run: dart pub get

      - name: Run build runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Compile Dart server for Linux
        # Usando o nome que você tinha para Linux
        run: dart compile exe bin/dnose.dart -o dnose_linux_amd64.exe

      - name: Upload Linux release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dnose_linux_amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-release-windows:
    name: Build for Windows
    runs-on: windows-latest
    permissions:
      contents: write # Necessário para o GITHUB_TOKEN fazer upload de assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Get dependencies
        run: dart pub get

      - name: Run build runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Compile Dart server for Windows
        run: dart compile exe bin/dnose.dart -o dnose_windows_amd64.exe

      - name: Upload Windows release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dnose_windows_amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}